#!/usr/bin/env bash
set -aeuo pipefail

# first build the image after cloning this repository
docker build -t apidoc/apidoc ./.docker/apidoc

# run apidoc
mkdir -p ./src/public/apidocs/
chmod -R 777 ./src/public/apidocs/
docker run --rm -v $(pwd):/home/node/apidoc apidoc/apidoc -c ./apidocs/config.json -i ./src/app/ -o ./src/public/apidocs/
