version: "3.7"

services:
  web:
    image: nginx:alpine
    ports:
      - 8083:80
    volumes:
      - ./src:/var/www/html
      - ./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
  phpfpm:
    build:
      context: ./docker
      dockerfile: php/Dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - www
    environment:
      XDEBUG_CONFIG: mode=debug client_host=host.docker.internal client_port=9003 start_with_request=yes output_dir=/tmp/grinds

networks:
  www:
