version: "3.7"

services:
  lumen_nginx:
    image: nginx:alpine
    ports:
      - 8083:80
    depends_on:
      - lumen_php
    environment:
      WAIT_HOSTS: lumen_php:9000
    volumes:
      - ./src/public:/var/www/html/public
      - ./.docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf

  lumen_php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      target: php
      args:
        # install xdebug when APP_ENV = local only
        APP_ENV: dev
    env_file:
      - ./.env
    volumes:
      - ./src:/var/www/html:delegated
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
      WAIT_HOSTS: lumen_cache:6379, lumen_db:3306
    depends_on:
      - lumen_cache
      - lumen_db
    command: sh -c "composer install && php-fpm"

  lumen_db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=domain
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - lumen-db:/var/lib/mysql
      - ./transfer:/docker-entrypoint-initdb.d:delegated

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=lumen_db
    ports:
      - 33060:8080

  lumen_cache:
    image: redis:alpine
    restart: always

volumes:
  lumen-db:
