# Start with a base file that defines the canonical configuration for the services.
version: "3.7"

services:
  lumen_nginx:
    image: ${ALIYUN_CONTAINER_REGISTRY}/${COMPOSE_PROJECT_NAME}_lumen_nginx
    container_name: ${COMPOSE_PROJECT_NAME}_lumen_nginx
    restart: always

  lumen_php:
    image: ${ALIYUN_CONTAINER_REGISTRY}/${COMPOSE_PROJECT_NAME}_lumen_php
    container_name: ${COMPOSE_PROJECT_NAME}_lumen_php
    restart: always

  lumen_db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  lumen_cache:
    image: redis:alpine
    restart: always

  adminer:
    image: adminer
    restart: "no"

  phpredisadmin:
    restart: "no"
