# Start with a base file that defines the canonical configuration for the services.
version: "3.7"

services:
  lumen_nginx:
    image: ${ALIYUN_CONTAINER_REGISTRY}/${COMPOSE_PROJECT_NAME}_lumen_nginx
    container_name: ${COMPOSE_PROJECT_NAME}_lumen_nginx
    restart: always

  lumen_php:
    image: ${ALIYUN_CONTAINER_REGISTRY}/${COMPOSE_PROJECT_NAME}_lumen_php
    container_name: ${COMPOSE_PROJECT_NAME}_lumen_php
    restart: always

  lumen_db:
    restart: "no"

  lumen_cache:
    restart: "no"

  adminer:
    restart: "no"

  phpredisadmin:
    restart: "no"
