# In the development configuration exposes some ports to the host,
# mounts our code as a volume, and builds the web image.
version: "3.7"

services:
  lumen_nginx:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      target: nginx
    ports:
      - 8080:80
    depends_on:
      - lumen_php
    volumes:
      - ./src/public:/var/www/html/public

  lumen_php:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
      target: php
      args:
        APP_ENV: ${APP_ENV}
    env_file: .env
    volumes:
      - ./src:/var/www/html:delegated
    environment:
      APP_DEBUG: ${APP_DEBUG}
      # XDEBUG_CONFIG: client_host=host.docker.internal
    depends_on:
      lumen_cache:
        condition: service_started
      lumen_db:
        condition: service_healthy

    command: sh -c "composer install && php-fpm"

  lumen_db:
    image: mysql:8
    restart: always
    command: "--log-error-suppression-list=MY-013360"
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=root --execute "SHOW DATABASES;"'
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      - MYSQL_DATABASE=domain
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - lumen-db:/var/lib/mysql
      - ./transfer:/docker-entrypoint-initdb.d:delegated

  lumen_cache:
    image: redis:alpine
    restart: always
    # command: --loglevel verbose

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=lumen_db
    ports:
      - 8081:8080

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    environment:
      - REDIS_1_HOST=lumen_cache
      - REDIS_1_PORT=6379
    depends_on:
      - lumen_cache
    ports:
      - 8082:80

volumes:
  lumen-db:
