version: "3.7"

services:
  web:
    image: nginx:alpine
    ports:
      - 8083:80
    volumes:
      - ./src:/var/www/html
      - ./.docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
  phpfpm:
    build:
      context: ./.docker
      dockerfile: php/Dockerfile
      args:
        # install xdebug when APP_ENV = local only
        APP_ENV: local
    volumes:
      - ./src:/var/www/html:delegated
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
