version: "3.7"

services:
  lumen_nginx:
    image: nginx:alpine
    ports:
      - 8083:80
    volumes:
      - ./src/public:/var/www/html/public
      - ./.docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf

  lumen_php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      args:
        # install xdebug when APP_ENV = local only
        APP_ENV: dev
    env_file:
      - ./.env
    volumes:
      - ./src:/var/www/html:delegated
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    command: sh -c "php-fpm"

  lumen_db:
    image: mysql:8
    restart: "no"
    restart: always
    ports:
      - 8084:3306
    volumes:
      - lumen-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=domain
      - MYSQL_ROOT_PASSWORD=rootroot
    volumes:
      - ./transfer:/docker-entrypoint-initdb.d:delegated

  lumen_cache:
    image: redis:5.0-alpine
    restart: always
    expose:
      - "6379"

volumes:
  lumen-db:

