#!/usr/bin/env bash

# create the dotenv file if it doesn't exist
if [ ! -f .env ]; then
  cp .env.default .env
fi

source .env

# lumen phpunit test
docker-compose run --rm \
    -e DB_CONNECTION=sqlite \
    -e DB_DATABASE="database/database.sqlite" \
    -e APP_ENV=testing \
    -e CACHE_DRIVER=array \
    -e JWT_SECRET=JWT_SECRET \
    -e JWT_TTL=7200 \
    -e QUEUE_CONNECTION=sync \
    lumen_php \
    sh -c "./vendor/bin/phpunit"
