#!/usr/bin/env bash

PHP_CONTAINER="$(docker ps -q -f NAME=lumen_php)"
docker exec -ti \
    -e DB_CONNECTION=sqlite \
    -e DB_DATABASE="database/database.sqlite" \
    -e APP_ENV=testing \
    -e CACHE_DRIVER=array \
    -e JWT_SECRET=JWT_SECRET \
    -e JWT_TTL=7200 \
    -e QUEUE_CONNECTION=sync \
    $PHP_CONTAINER \
    sh -c "./vendor/bin/phpunit $*"
