apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mysql/volume.yaml
  - mysql/deployment.yaml
  - mysql/service.yaml
  - redis/deployment.yaml
  - redis/service.yaml

configMapGenerator:
- name: public-db
  literals:
  - DB_CONNECTION=mysql

secretGenerator:
- name: secrets-db
  env: secrets.txt
  type: Opaque
